[variables]
NODE_ENV = 'production'

[phases.build]
cmds = ['npm run build', 'mkdir -p /app/workspace-sandbox/projects', 'touch /app/vnp-users-db.json', 'chmod -R 777 /app/workspace-sandbox', 'chmod 777 /app/vnp-users-db.json']

[start]
cmd = 'npm start'
